const baseStrategy = {
  exit_conditions: ["Exit at planned stop, target, session square-off, or risk lock."],
  backtesting_requirements: ["Use clean MCX futures data, costs, slippage, and contract rollover rules."],
  live_execution_considerations: ["Use closed candles, fresh WebSocket data, broker health checks, and idempotent order keys."],
};

export const mcxFallbackCatalog = {
  product_name: "MCX Strategy Lab",
  product_category: "Algorithmic commodity strategy research and execution blueprint",
  one_line_pitch: "Rule-based MCX commodity strategies designed for broker API execution with risk controls first.",
  market: "Indian Multi Commodity Exchange (MCX)",
  source: "bundled_fallback",
  commodities: [
    { symbol: "CRUDEOIL", name: "Crude Oil", traits: ["high liquidity", "news sensitive", "trend friendly"] },
    { symbol: "NATURALGAS", name: "Natural Gas", traits: ["high volatility", "gap risk", "breakout friendly"] },
    { symbol: "GOLD", name: "Gold", traits: ["macro driven", "liquid", "cleaner trends"] },
    { symbol: "SILVER", name: "Silver", traits: ["volatile", "trend bursts", "risk-on/risk-off"] },
    { symbol: "COPPER", name: "Copper", traits: ["industrial demand", "session momentum", "lower noise"] },
  ],
  top_3: [],
  strategies: [
    {
      ...baseStrategy,
      id: "mcx_opening_range_breakout",
      rank: 1,
      strategy_name: "MCX Opening Range Breakout",
      market_logic: "Trade the first confirmed break of a defined MCX session range with ATR, volume, and VWAP confirmation.",
      suitable_commodities: ["CRUDEOIL", "NATURALGAS", "GOLD", "SILVER"],
      timeframe: "5m execution with 15m confirmation",
      entry_conditions: [
        "Build the first 30-minute session range.",
        "Buy above range high or sell below range low only after candle close.",
        "Require breakout candle range above 0.8 x ATR(14) and VWAP/EMA trend alignment.",
      ],
      stop_loss_logic: "Stop beyond the opposite side of the opening range or 1.2 x ATR(14).",
      target_logic: "Target 1.8R to 2.5R with ATR or EMA trailing after 1R.",
      risk_reward_ratio: "1:1.8 to 1:2.5",
      expected_win_rate_range: "38% to 48%",
      best_market_conditions: ["directional evening session", "global liquidity", "clean breakout candles"],
      worst_market_conditions: ["tight range", "false news spikes", "low liquidity"],
      required_indicators: ["Opening Range", "ATR(14)", "VWAP", "EMA(20)", "Volume"],
      parameter_values: { range_minutes: 30, atr_period: 14, breakout_atr_multiple: 0.8, max_trades_per_day: 2 },
      scores: { simplicity: 92, robustness: 90, scalability: 88, automation: 95, mcx_fit: 94 },
    },
    {
      ...baseStrategy,
      id: "mcx_volatility_expansion",
      rank: 2,
      strategy_name: "ATR Volatility Expansion Breakout",
      market_logic: "Wait for compressed volatility, then trade the first Donchian breakout with volume expansion.",
      suitable_commodities: ["CRUDEOIL", "NATURALGAS", "SILVER", "COPPER"],
      timeframe: "15m",
      entry_conditions: [
        "ATR percentile is below 35 before breakout.",
        "Bollinger Band width is compressed.",
        "Enter on Donchian(20) close breakout with volume above SMA(20).",
      ],
      stop_loss_logic: "Use 1.5 x ATR(14) from entry or signal candle extreme.",
      target_logic: "Partial at 1.5R and trail final quantity with 2 x ATR.",
      risk_reward_ratio: "1:2 to 1:3",
      expected_win_rate_range: "34% to 44%",
      best_market_conditions: ["volatility compression", "post-consolidation breakout", "high participation"],
      worst_market_conditions: ["headline chop", "wide spreads", "late-session exhaustion"],
      required_indicators: ["ATR percentile", "Donchian(20)", "Bollinger Band Width", "Volume SMA(20)"],
      parameter_values: { atr_period: 14, atr_percentile_max: 35, donchian_period: 20, stop_atr_multiple: 1.5 },
      scores: { simplicity: 84, robustness: 91, scalability: 89, automation: 90, mcx_fit: 92 },
    },
    {
      ...baseStrategy,
      id: "mcx_trend_pullback_atr",
      rank: 3,
      strategy_name: "ATR Trend Pullback Continuation",
      market_logic: "Join established commodity trends on pullbacks to VWAP or EMA instead of chasing extended candles.",
      suitable_commodities: ["GOLD", "SILVER", "CRUDEOIL", "COPPER"],
      timeframe: "15m bias, 5m execution",
      entry_conditions: [
        "EMA(20) and EMA(50) define trend direction.",
        "ADX(14) above 22 confirms trend strength.",
        "Enter on rejection from VWAP or EMA(20) in trend direction.",
      ],
      stop_loss_logic: "Stop beyond pullback swing plus 0.5 x ATR(14).",
      target_logic: "Target 1.5R to 2.5R near previous swing extension.",
      risk_reward_ratio: "1:1.5 to 1:2.5",
      expected_win_rate_range: "42% to 52%",
      best_market_conditions: ["clean trend", "global alignment", "steady volume"],
      worst_market_conditions: ["range market", "VWAP whipsaws", "news reversals"],
      required_indicators: ["EMA(20)", "EMA(50)", "VWAP", "ADX(14)", "ATR(14)"],
      parameter_values: { fast_ema: 20, slow_ema: 50, adx_min: 22, stop_buffer_atr_multiple: 0.5 },
      scores: { simplicity: 86, robustness: 88, scalability: 86, automation: 88, mcx_fit: 89 },
    },
    {
      ...baseStrategy,
      id: "mcx_session_momentum",
      rank: 4,
      strategy_name: "London-US Session Momentum",
      market_logic: "Trade only during high-liquidity global overlap windows when MCX commodities become directional.",
      suitable_commodities: ["CRUDEOIL", "NATURALGAS", "GOLD", "SILVER", "COPPER"],
      timeframe: "15m",
      entry_conditions: ["Trade configured MCX evening sessions only.", "Break previous session high/low with RSI confirmation."],
      stop_loss_logic: "Stop behind signal candle or 1.2 x ATR(14).",
      target_logic: "Fixed 1.8R target with optional ATR trail.",
      risk_reward_ratio: "1:1.8",
      expected_win_rate_range: "40% to 50%",
      best_market_conditions: ["London-US overlap", "macro trend alignment"],
      worst_market_conditions: ["holiday sessions", "thin volume"],
      required_indicators: ["Session high/low", "RSI(14)", "ATR(14)", "Volume"],
      parameter_values: { rsi_period: 14, long_rsi_min: 55, short_rsi_max: 45, target_r_multiple: 1.8 },
      scores: { simplicity: 88, robustness: 82, scalability: 90, automation: 92, mcx_fit: 86 },
    },
    {
      ...baseStrategy,
      id: "mcx_donchian_trend",
      rank: 5,
      strategy_name: "Donchian Trend Rider",
      market_logic: "Enter new 20-period highs/lows and ride larger commodity trends with trailing exits.",
      suitable_commodities: ["CRUDEOIL", "GOLD", "SILVER", "COPPER"],
      timeframe: "30m or 1h",
      entry_conditions: ["Long above Donchian(20) high.", "Short below Donchian(20) low.", "Avoid extreme ATR percentile."],
      stop_loss_logic: "Initial stop at 2 x ATR(14).",
      target_logic: "No fixed target; exit using Donchian(10) trailing channel.",
      risk_reward_ratio: "Variable, designed for 3R+ winners",
      expected_win_rate_range: "30% to 42%",
      best_market_conditions: ["multi-day trend", "macro continuation"],
      worst_market_conditions: ["sideways range", "false breakouts"],
      required_indicators: ["Donchian(20)", "Donchian(10)", "ATR(14)"],
      parameter_values: { entry_channel: 20, exit_channel: 10, stop_atr_multiple: 2 },
      scores: { simplicity: 80, robustness: 84, scalability: 85, automation: 86, mcx_fit: 80 },
    },
    {
      ...baseStrategy,
      id: "mcx_vwap_mean_reversion",
      rank: 6,
      strategy_name: "VWAP Deviation Mean Reversion",
      market_logic: "Fade extreme VWAP deviations only when ADX confirms a non-trending market.",
      suitable_commodities: ["GOLD", "SILVER", "COPPER"],
      timeframe: "5m",
      entry_conditions: ["ADX(14) below 18.", "Price rejects 2 standard deviation VWAP band.", "No high-impact event nearby."],
      stop_loss_logic: "Stop beyond rejection candle plus 0.5 x ATR(14).",
      target_logic: "VWAP touch or 1.2R.",
      risk_reward_ratio: "1:1 to 1:1.3",
      expected_win_rate_range: "52% to 62%",
      best_market_conditions: ["range-bound sessions", "post-news stabilization"],
      worst_market_conditions: ["strong trend days", "one-way gas moves"],
      required_indicators: ["VWAP bands", "ADX(14)", "ATR(14)"],
      parameter_values: { vwap_band_stddev: 2, adx_max: 18, trend_abort_adx: 24 },
      scores: { simplicity: 78, robustness: 76, scalability: 78, automation: 82, mcx_fit: 74 },
    },
  ],
  complete_trading_rules: [
    "Trade only enabled MCX symbols, valid contracts, and configured sessions.",
    "Generate signals only from closed candles.",
    "Validate broker login, WebSocket freshness, quotes, risk limits, and duplicate locks before orders.",
    "Risk per trade is fixed before entry and converted to exchange lot size.",
    "Place protective stop immediately after entry fill.",
    "No martingale, no averaging down, and no quantity increase after loss.",
  ],
  state_machine: [
    { state: "DISABLED", description: "Saved but not eligible for signal generation." },
    { state: "WARMING_UP", description: "Candles and live data are loading." },
    { state: "READY", description: "Broker, data, session, and risk checks are healthy." },
    { state: "SIGNAL_DETECTED", description: "Closed candle satisfies entry rules." },
    { state: "ORDER_PENDING", description: "Order sent and waiting for broker acknowledgement." },
    { state: "IN_POSITION", description: "Position is open and protective exits are active." },
    { state: "LOCKED", description: "Risk or infrastructure guard stopped trading." },
  ],
  pseudocode: [
    "load active MCX strategies",
    "update candles from WebSocket ticks",
    "on candle close validate session, broker, feed, and risk",
    "compute indicators and generate signal",
    "calculate stop, target, quantity, and idempotency key",
    "submit order through broker adapter",
    "monitor stop, target, trail, square-off, and reconciliation",
  ],
  database_schema_requirements: [
    { table: "mcx_strategy_templates", purpose: "Stores reusable strategy definitions.", key_fields: ["id", "name", "version", "parameters"] },
    { table: "mcx_strategy_instances", purpose: "Stores user-specific strategy settings.", key_fields: ["id", "user", "template_id", "symbol", "risk_per_trade"] },
    { table: "mcx_signal_events", purpose: "Auditable signal log.", key_fields: ["id", "instance_id", "signal_side", "state", "skip_reason"] },
    { table: "mcx_order_executions", purpose: "Broker request and response lifecycle.", key_fields: ["id", "signal_id", "broker_order_id", "status", "public_ip"] },
    { table: "mcx_risk_snapshots", purpose: "Daily risk state.", key_fields: ["id", "user", "date", "realized_pnl", "daily_lock"] },
  ],
  api_execution_flow: [
    "Frontend enables strategy settings.",
    "FastAPI validates and stores configuration.",
    "Worker subscribes to MCX WebSocket symbols.",
    "Risk engine blocks unsafe orders.",
    "Broker adapter sends AliceBlue, Dhan, or Zerodha orders.",
    "Reconciliation jobs verify orders, positions, and P&L.",
  ],
  risk_management_framework: {
    risk_per_trade: "0.25% to 1% of capital",
    daily_loss_limit: "2% of capital or user-defined rupee amount",
    max_trades_per_day: "2 to 4 per symbol",
    max_open_positions: "1 per commodity family unless portfolio risk allows more",
    kill_switches: ["broker disconnected", "WebSocket stale", "IP restriction", "stop order failed", "daily loss reached"],
  },
  disclaimer: "Bundled fallback shown because the backend catalog endpoint is unavailable. Deploy the backend route for the full source-of-truth catalog.",
};

mcxFallbackCatalog.top_3 = mcxFallbackCatalog.strategies.filter((strategy) => strategy.rank <= 3);
